#!/usr/bin/env python3
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
cmake = (root / "ide/CMakeLists.txt").read_text(encoding="utf-8")
controller = (root / "ide/BuildController.cpp").read_text(encoding="utf-8")

generated = set(re.findall(r'inline constexpr const char\*\s+(\w+)\s*=', cmake))
used = set(re.findall(r'SmallBuildConfig::(\w+)', controller))
# QtLibraries is an array, not const char*.
generated.update(re.findall(r'inline constexpr const char\*\s+(\w+)\s*\[\]', cmake))

missing = sorted(used - generated)
if missing:
    raise SystemExit("BuildController uses fields not generated by CMake: " + ", ".join(missing))

required = {"Compiler", "CompilerId", "CompilerVersion", "QtBin", "RuntimeFile", "EntryFile", "QtLibraries"}
missing_required = sorted(required - generated)
if missing_required:
    raise SystemExit("SmallBuildConfig is missing required fields: " + ", ".join(missing_required))

print("SmallBuildConfig consistency passed:", ", ".join(sorted(generated)))
